### ISSUE TITLE
Support a ARM image

### ISSUE THREAD

**Issue by holysoles** [holysoles/ginrcon#16]
This image isnt able to be run on ARM64, such as Raspberry Pis.

Best path is probably supporting an additional docker image that is built for arm 64

https://docs.docker.com/build/building/multi-platform/#cross-compilation

**Comment by Bluscream** [comment]
I just wanted to ask this before i saw this issue, i'm getting exec format errors

**Comment by holysoles** [comment]
@Bluscream this should be all set now, tested this out on my Pi 4 running Raspberry Pi 11. Feel free to open another issue if you run into any problems!

**Comment by Bluscream** [comment]
```yaml
version: '3.9'
services:
  ginrcon:
    image: ghcr.io/holysoles/ginrcon:latest
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "8085:8080/tcp"
    # environment:
      # PORT: 8080
      # TRUSTED_PROXIES: "192.168.1.2"
      # RCON_SERVER: localhost
      # RCON_PORT: 7779
      # RCON_ADMIN_PASSWORD: 1234
```

**Comment by holysoles** [comment]
@Bluscream  can you check what bit architecture your rpi is running with this command?

`getconf LONG_BIT`

My raspberry pi is 32bit and I can reproduce your error when I use your compose file, but not when i dont specify the `platform` key like below. You shouldnt need to specify that yourself, Docker should normally resolve it automatically.

```yaml
version: '3.9'
services:
  ginrcon:
    image: ghcr.io/holysoles/ginrcon:latest
    restart: unless-stopped
    ports:
      - "8085:8080/tcp"
    # environment:
      # PORT: 8080
      # TRUSTED_PROXIES: "192.168.1.2"
      # RCON_SERVER: localhost
      # RCON_PORT: 7779
      # RCON_ADMIN_PASSWORD: 1234
```
